// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNJ3KHXqRxzFyKJC2mD8f450czr0L7TH4',
    appId: '1:480494136531:web:dfc081d7e8936bc4213826',
    messagingSenderId: '480494136531',
    projectId: 'curd-6309b',
    authDomain: 'curd-6309b.firebaseapp.com',
    databaseURL: 'https://curd-6309b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'curd-6309b.appspot.com',
    measurementId: 'G-8F8KDGKQCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwkgKDt8yh_4KyTJzzyxGSDALqe9qqzxE',
    appId: '1:480494136531:android:09d7cd8fd99aba82213826',
    messagingSenderId: '480494136531',
    projectId: 'curd-6309b',
    databaseURL: 'https://curd-6309b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'curd-6309b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2LheJxXoMfa24RKSTQykJ_YnSkc0B-1E',
    appId: '1:480494136531:ios:97749b7d231cc9d2213826',
    messagingSenderId: '480494136531',
    projectId: 'curd-6309b',
    databaseURL: 'https://curd-6309b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'curd-6309b.appspot.com',
    iosBundleId: 'com.aniket.curd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2LheJxXoMfa24RKSTQykJ_YnSkc0B-1E',
    appId: '1:480494136531:ios:6e14d572bf519e30213826',
    messagingSenderId: '480494136531',
    projectId: 'curd-6309b',
    databaseURL: 'https://curd-6309b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'curd-6309b.appspot.com',
    iosBundleId: 'com.aniket.curd.RunnerTests',
  );
}
